### ISSUE TITLE
Update SDF API

### ISSUE THREAD

**Issue by ugeorge** [forsyde/forsyde-shallow#22]
Since we make an API-breaking revision, I would like to propose we take out `delaySDF` which seems to be redundant, and replaceable by `delaynSDF`. 

* judging by SDF MoC semantics it makes no sense to have a separate constructor for one initial token and another one for multiple initial tokens. 
* `delatnSY` behaves completely different than `delaynSDF`, and has different semantics to start with. Having the same name for so different constructors again makes no sense.
* @ricardobonna has already implemented `delayCSDF` and `delaySADF` based on the `delaynSDF` model. 

So, my proposal is to dump `delaySDF` and to rename `delaynSDF` to `delaySDF`.

**Comment by ingo-sander** [comment]
OK, I agree to the changes. It makes sense, although it will break some existing examples (for instance in the book chapter). But it is good, if we have the same format as in CSDF and SADF! So, please integrate the changes!
