### ISSUE TITLE
update CI

### ISSUE THREAD

**Issue by ugeorge** [forsyde/forsyde-shallow#6]
There are a few issues with the current CI schema:

 * does not cover the [Hackage Matrix CI](https://matrix.hackage.haskell.org/package/forsyde-shallow) scheme, more exactly it fails to build with ghc-7.4
 * does not have a test suite yet

**Comment by ugeorge** [comment]
I propose using functions from the [`MulAcc`](https://github.com/forsyde/forsyde-shallow-examples/blob/master/src/ForSyDe/Shallow/Example/Synchronous/MulAcc.hs), [`FibbonaciRabbits`](https://github.com/forsyde/forsyde-shallow-examples/blob/master/src/ForSyDe/Shallow/Example/Synchronous/FibonacciRabbits.hs), [`AdaptiveAmp`](https://github.com/forsyde/forsyde-shallow-examples/blob/master/src/ForSyDe/Shallow/Example/Untimed/AdaptiveAmp.hs) and [`Ascii2Bin`](https://github.com/forsyde/forsyde-shallow-examples/blob/master/src/ForSyDe/Shallow/Example/Untimed/Ascii2Bin.hs) examples for the unit tests for v3.3.2. For now it should be enough, as the synchronous and untimed MoCs are the most stable. We will plan unit tests and property checks for other modules in future iterations.

**Comment by ingo-sander** [comment]
Fine! Go ahead!
